### ISSUE TITLE
获取日线历史数据时，我在22-11-08号调用的却只能获取到2022-10-24之前的数据？最近半个月没有数据吗？

### ISSUE THREAD

**Issue by zl-fire** [andyesfly/dipiper#9]
随机看了10个左右的股票数据，好像都是这样...

<img width="1372" alt="image" src="https://user-images.githubusercontent.com/25565146/200530154-7cbfeb52-b099-460e-9a65-dd15dd9540f5.png">
<img width="635" alt="image" src="https://user-images.githubusercontent.com/25565146/200531320-a3143c3e-abf1-4b8f-8f9f-f1f07ead81ef.png">

**Comment by andyesfly** [comment]
抱歉，这个项目已不再维护
